### ISSUE TITLE
[Suggestion] - add svg sprite loader

### ISSUE THREAD

**Issue by sp90** [lukeed/preact-starter#10]
First off, great project - thanks 🥇 

Its really nice to work with the svg-sprite-loader for icons instead of fonts, now we have killed support for IE8 by going down the preact lane anyway 👍

**Comment by lukeed** [comment]
Hi! Thank you 😄 

I'm not sure what to do in this case. This starter currently doesn't load any fonts or icons, so I don't feel it's directly needed. _Also_ (mainly) I'm not sure if I want to force people in one direction or another. 

Personally, I still cycle between the `url-loader` and `file-loader`. Rarely I'll use `svg-sprites`, simply because I typically generate custom icon fonts. 😅 And in the event I'm using SVGs directly, it's generally less than 5 total, so I link to them directly.

I dunno, maybe it's my own mistake? But I still don't think SVG sprites are common _enough_ that 90% of downloads will use them.

**Comment by sp90** [comment]
thats great and all, i've also used icon fonts in a very long time, but its outdated, and i do agree it could be out of scope for this boilerplate.

I normally use svg-sprites with this component in react - i guess a simple rewrite could be done for preact aswell.

https://gist.github.com/sp90/cfcba9d446ae33148af12c41903c8eae

Anyhow thats totally up to you if you wanna go one way or the other

**Comment by lukeed** [comment]
I think I'm going to have to pass this time around, but thank you @sp90! Maybe in the future 😄
