### ISSUE TITLE
Update changes not working

### ISSUE THREAD

**Issue by Alex-DG** [lukeed/preact-starter#17]
Hi,

I've been through preact-starter to learn more about PWA. I want to see how the cache-busting and the pwa will update my changes. 
I've set up an heroku app based on the preact starter repo code, then I'm trying to change some text within the home page and pushing my changes:

- On my chrome browser the updated version is never shown it's like the cache is no updating at all, even after a page refresh (I have to clear site data to see the latest version). When I'm going through my files on the server: heroku run bash > cat home.js, I can see the component is up to date, like on my local, but the page is not showing the latest version.

- On an Android phone (still using chrome), if I refresh the PWA, I can see the updated text on the home page but I was thinking the 'cache busting' should handle update, without the need to refresh manually the page by the user ?

Just wanted to double check with you if you have any thoughts about my current issues, I'm definitely missing something, but can't figure out where. 

heroku: [preact-starter](https://preact-starter.herokuapp.com/)
git: [test-preact-starter](https://github.com/Alex-DG/test-preact-starter)

Thanks for your time,
Alex.

**Comment by lukeed** [comment]
Hey Alex, thanks!

This is because your Heroku server is caching the `service-worker.js` file, which is the main _gotcha_ for Service Workers.

<img width="479" alt="screen shot 2017-09-18 at 8 25 25 am" src="https://user-images.githubusercontent.com/5855893/30550139-6dd8548a-9c4b-11e7-8585-537a1040f6e1.png">

You have to turn off caching for the SW file specifically, as this is the only way that the SW can discern if there's a newer version of itself. 

If cached, the following `/service-worker.js` requests, will all return the same content with the same versioning info (and the same assets cache definition), which tells the registered SW that there is _not_ anything new to worry about, so nothing changes.

Hope that helps!

**Comment by Alex-DG** [comment]
Thank you very much for your help on it, @lukeed ! 

From my understanding I need to specify something like cache-control:private, max-age=0, no-cache in my sw header.

**Comment by Alex-DG** [comment]
In case someone has the same issue I had here what I've done :

So far I was using _Heroku_, I struggled a bit to handle this cache-control I figured out you can add a no cache param to `serve`(check [there](https://github.com/zeit/serve/blob/8c1eec9ed4c78cacf3735ed8ed482a746724baff/lib/options.js#L11)). I was not really satisfied. So I look for others possibilities, I came across _Firebase_ where you can actually very easily doing this headers configuration through a `firebase.json` file, it works like a charm now.

**Comment by lukeed** [comment]
Yeah, I forget you can't specify headers with `serve` -- maybe I'll look into PR'ing that. Most static-servers will let you configure headers, like Firebase hosting.

Thanks for following up~!
