### ISSUE TITLE
props and states

### ISSUE THREAD

**Issue by mehmetkose** [lukeed/preact-starter#18]
Hey looked I'm confused here, 

I want to pass states as props here, but I couldn't figure out how can I transform function to class. Any little help?

![screen shot 2017-09-23 at 17 29 44](https://user-images.githubusercontent.com/706678/30774023-f7b312de-a084-11e7-8467-88ed735b3341.png)

**Comment by lukeed** [comment]
Hey,

I've exported that file as a variable because the starter app doesn't need anything more complex.

For your case, you'll want to convert this to a export a stateful component and update the main function.

***Export Stateful Component***

```js
import { h, Component } from 'preact';
//...
export class App extends Component {
  // ...
  render(props, state) {
    return (
      <Layout>
        // ... <Router>....</Router>
      </Layout>
    );
  }
}
```

***Update Main Import***

Change [this line](https://github.com/lukeed/preact-starter/blob/master/src/index.js#L8) to:

```js
elem = render(h(App), document.getElementById('root'), elem);
// or
elem = render(<App/>, document.getElementById('root'), elem);
```

I have a real-world example using this starter kit. You can look at [`colors-app`](https://github.com/lukeed/colors-app/tree/master/src) to see how I've done what you're after.

Hope that helps!

**Comment by mehmetkose** [comment]
Yup that will help Thanks Luke!
