### ISSUE TITLE
adding google maps preact way

### ISSUE THREAD

**Issue by mehmetkose** [lukeed/preact-starter#21]
hi, 
I'm looking for google maps component but I don't know know how to write **preact** way.
I liked your **ganalytics** package, however I couldn't read how can I build like this.

any idea?

**Comment by lukeed** [comment]
Hey, thanks!

To be honest, I've only used Google Maps a couple times & never did anything intensive with it. I just use the official JS API & config. So, what you can do is extend `Component` to load the script on `componentWillMount` & then setup the Component to accept config options. Then you _might_ want to disable `shouldComponentUpdate` since gmaps will be controlling the actual map.

If you need something intense, may be you should check out [`react-google-maps`](https://github.com/tomchentw/react-google-maps). I've never used it, but you should be able to use it just fine -- even if it means loading up `preact-compat`.

Hope that helps!
